### PR TITLE
Fix file name rendering when dir ends with /

### LINKED ISSUE #290: Issue with the frontend: first file is called "ebug.c" (should be "debug.c")
https://coverage.moz.tools/#revision=latest&path=media/mtransport/third_party/nrappkit/src/util/libekr/

### PR DESCRIPTION
**Pull request by La0**
fixes #290

Silly bug :sob:

### CODE REVIEW

File: frontend/src/index.js [hunk 1]
```diff
@@ -124,7 +124,13 @@ async function showDirectory(dir, revision, files) {
     revision: revision || REV_LATEST,
     file_name() {
       // Build filename relative to current dir
-      return dir ? this.path.substring(dir.length + 1) : this.path;
+      if (dir) {
+        // Remove extra / only when present
+        const offset = dir.substring(dir.length - 1) === "/" ? 0 : 1;
```
Comment (marco-c) [inline frontend/src/index.js]: Nit: no need to get a substring here, just compare the last character: `dir[dir.length - 1] === "/"`.

Comment (La0) [reply frontend/src/index.js]: This is how i know it's time to head back home. Thanks

**Comment by La0** [comment]
[Works on the artifact build](https://community.taskcluster-artifacts.net/KZjGI3xEQVKahQGS16azlg/0/public/frontend/index.html#revision=latest&path=media/mtransport/third_party/nrappkit/src/util/libekr/)
